source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
target 'TestSwiftScan' do
    use_frameworks!
#pod 'swiftScan'
pod 'swiftScan', :git => 'https://github.com/MxABC/swiftScan.git', :tag => '1.0.9'
end
