source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
platform :ios, '8.1'
target ‘TestAlamofire’ do
    use_frameworks!
pod 'SnapKit', '~> 4.0.0'
pod 'Alamofire', '~> 4.5.1’
end
