source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
target 'TestFDTemplateLayoutCell' do
    use_frameworks!
pod 'UITableView+FDTemplateLayoutCell', '~>1.5.beta'
pod 'SnapKit', '~> 3.2.0'
end
