source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
source 'http://git.ops.com/XGN-IOS/xgn.git'
platform :ios, '8.1'
target ‘TestVine’ do
    use_frameworks!
pod 'SnapKit', '~> 4.0.0'
pod 'HandyJSON', '= 4.0.0-beta.1'
pod 'XBLogger', '= 1.2.1'
pod 'SwiftyJSON', '= 3.1.4'
pod 'Alamofire', '~> 4.5.1’
end
