source 'http://git.ops.com/XGN-IOS/xgn.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
platform :ios, '8.1'
target ‘TestFrameMVVM’ do
    use_frameworks!
pod 'SnapKit', '~> 4.0.0'
pod 'HandyJSON', '= 4.0.0-beta.1'
pod 'Vine', '= 2.0.2'
pod 'Kvstore', '= 1.0.5'
end
